/**
 * Matière du sol (D-125) : ce sur quoi Céleste se tient, pour la poussière (et plus tard les bruits
 * de pas, chantier B). Elle se lit d'abord dans le meuble sous ses pieds (`DECOR_SURFACE`), puis
 * dans le matériau de la tuile, puis dans le sol de la salle (`ROOM_GROUND`). PROVISOIRE : choix
 * d'après le dessin des salles, à corriger au besoin.
 */
export const Surface = {
  Wood: 'wood',
  Fabric: 'fabric',
  Grass: 'grass',
  Stone: 'stone',
  Sand: 'sand',
  Metal: 'metal',
  Leaves: 'leaves',
} as const;
export type Surface = (typeof Surface)[keyof typeof Surface];

const { Wood, Fabric, Grass, Stone, Sand, Metal, Leaves } = Surface;

/**
 * Meubles (`DECOR_KINDS`) qui ne sont pas en bois. Un meuble absent de la liste prend le matériau
 * de ses tuiles (`b` bois, `t` tissu, `v` feuillage).
 */
export const DECOR_SURFACE: Readonly<Partial<Record<string, Surface>>> = {
  // Tissu : lits, canapés, couchettes, valises, toiles.
  bed: Fabric,
  sofa: Fabric,
  pouf: Fabric,
  rolledrug: Fabric,
  bunks: Fabric,
  colonybunk: Fabric,
  carbench: Fabric,
  suitcases: Fabric,
  floatsuitcase: Fabric,
  suitcasestack: Fabric,
  lostpile: Fabric,
  awning: Fabric,
  kioskawning: Fabric,
  fairawning: Fabric,
  bigtop: Fabric,
  // Feuillage.
  hedge: Leaves,
  bush: Leaves,
  canopy: Leaves,
  nest: Leaves,
  // Terre et herbe des bacs.
  planter: Grass,
  windowbox: Grass,
  // Sable et vase.
  sandbox: Sand,
  wetsand: Sand,
  upperbeach: Sand,
  sandstep: Sand,
  harbourmud: Sand,
  // Pierre, béton, carrelage, faïence.
  counter: Stone,
  flowerpot: Stone,
  oldwall: Stone,
  sill: Stone,
  cornice: Stone,
  concretewall: Stone,
  hopscotch: Stone,
  quay: Stone,
  pillar: Stone,
  vault: Stone,
  plinth: Stone,
  colonybalcony: Stone,
  colonyroof: Stone,
  searock: Stone,
  keeperfloor: Stone,
  lampfloor: Stone,
  lighthousewall: Stone,
  breakwaterwalk: Stone,
  harbourquay: Stone,
  strangeseawall: Stone,
  dishstack: Stone,
  // Métal.
  hood: Metal,
  machine: Metal,
  fridge: Metal,
  fridgetop: Metal,
  potrack: Metal,
  ceilinglamp: Metal,
  car: Metal,
  bins: Metal,
  lamppost: Metal,
  busstop: Metal,
  shopsign: Metal,
  scaffold: Metal,
  roundabout: Metal,
  climbingdome: Metal,
  swingset: Metal,
  slidetower: Metal,
  schoolfence: Metal,
  cooler: Metal,
  shelfunit: Metal,
  cartonrack: Metal,
  stockshelf: Metal,
  crane: Metal,
  banche: Metal,
  antenna: Metal,
  floodlight: Metal,
  gymgable: Metal,
  fireescape: Metal,
  preau: Metal,
  basketball: Metal,
  strangestove: Metal,
  shelter: Metal,
  gantry: Metal,
  luggagecart: Metal,
  signalbox: Metal,
  footbridge: Metal,
  gallery: Metal,
  spiralstair: Metal,
  balcony: Metal,
  lockers: Metal,
  tallcabinet: Metal,
  wagon: Metal,
  cranehook: Metal,
  accordiongate: Metal,
  rack: Metal,
  trolley: Metal,
  bike: Metal,
  hookrail: Metal,
  highshelf: Metal,
  carroof: Metal,
  gangway: Metal,
  roofvent: Metal,
  kitchenchimney: Metal,
  freezer: Metal,
  icekiosk: Metal,
  roofsign: Metal,
  buoy: Metal,
  beacon: Metal,
  lighthousestair: Metal,
  lens: Metal,
  quayladder: Metal,
  harbourcrane: Metal,
  jettyladder: Metal,
  horsepole: Metal,
  cantower: Metal,
};

/**
 * Sol de chaque salle de zone, là où aucun meuble ni matériau ne dit autre chose (le dessin : herbe
 * au jardin, pavés en ville, parquet dans les maisons). Les parcours d'essai et les souvenirs
 * jouables prennent `DEFAULT_GROUND`.
 */
export const ROOM_GROUND: Readonly<Record<string, Surface>> = {
  bedroom: Wood,
  hall: Wood,
  staircase: Wood,
  living: Wood,
  kitchen: Stone,
  laundry: Stone,
  attic: Wood,
  'living-strange': Wood,
  shadows: Wood,
  'garden-terrace': Grass,
  'garden-vegetables': Grass,
  'garden-tree': Grass,
  'garden-treehouse': Wood,
  'garden-alley': Grass,
  'garden-upside': Grass,
  'garden-thorns': Grass,
  street: Stone,
  playground: Stone,
  shop: Stone,
  site: Stone,
  schoolyard: Stone,
  school: Wood,
  'school-strange': Wood,
  'station-tracks': Stone,
  'station-platforms': Stone,
  'station-hall': Stone,
  'station-lost': Wood,
  'station-depot': Stone,
  'station-strange': Stone,
  'station-tower': Stone,
  'train-couchettes': Fabric,
  'train-compartments': Fabric,
  'train-baggage': Wood,
  'train-roof': Metal,
  'train-restaurant': Wood,
  'train-strange-kitchen': Stone,
  'train-strange-dishes': Stone,
  'sea-station': Stone,
  'sea-promenade': Stone,
  'sea-centre': Wood,
  'sea-beach': Sand,
  'sea-rocks': Stone,
  'sea-lighthouse': Stone,
  'sea-port': Stone,
  'sea-jetty': Wood,
  'sea-strange-fair': Wood,
  'sea-strange-wave': Wood,
  'sea-corridor': Wood,
  'sea-corridor-sand': Sand,
  'sea-corridor-room': Wood,
  'sea-corridor-station': Stone,
  'sea-corridor-sea': Sand,
  'nanny-entry': Wood,
  'nanny-house': Wood,
  'nanny-bed': Wood,
  'nanny-garden': Grass,
  'nanny-school': Wood,
  'nanny-street': Stone,
  'nanny-station': Stone,
  'nanny-train': Metal,
  'nanny-beach': Sand,
  'nanny-carousel': Wood,
  'nanny-nap': Wood,
  'nanny-stairs': Wood,
  'nanny-playroom': Wood,
  // Le dernier niveau (D-141) : le parquet de la chambre, démesuré.
  'finale-bed': Wood,
  'finale-sky': Wood,
};

/** Sol des salles absentes de `ROOM_GROUND` (parcours d'essai, souvenirs jouables). */
export const DEFAULT_GROUND: Surface = Wood;

/**
 * Sous les pieds : la matière se lit à cette profondeur sous la hitbox (px). Au décollage, les pieds
 * ont déjà quitté le sol de quelques pixels.
 */
export const SURFACE_PROBE_PX = 4;
